on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Multicraft script
      uses: wei/curl@v1
      with:
        args: >-
          --location '${{  secrets.MULTICRAFT_API }}'
          --header 'Content-Type: application/x-www-form-urlencoded'
          --data-urlencode '_MulticraftAPIMethod=runScript'
          --data-urlencode '_MulticraftAPIUser=${{  secrets.MULTICRAFT_USER }}'
          --data-urlencode 'daemon_id=1'
          --data-urlencode 'script=updateDvzResourcepack'
          --data-urlencode 'args='
          --data-urlencode '_MulticraftAPIKey=${{  secrets.MULTICRAFT_KEY }}'
